### ISSUE TITLE
Raspberry Pi? 

### ISSUE THREAD

**Issue by captainsalvos** [danielkihlgren/stagedisplayviewer#13]
I'm trying to get this working on a raspberry pi,  it would be a fantastic embedded option if I could get it all working.  

At the moment I keep getting the error: 

"Could not find or load man class se.pingstteknik.propresenter.stagedisplayviewer.Main"

Is it possible to get working?  I have downloaded and installed Oracle's JDK 8 and that works fine.

**Comment by danielkihlgren** [comment]
What command are you using when running the program? I don't have a raspberry pi to test this on.

**Comment by danielkihlgren** [comment]
It seems that new releases of Oracle's JDK 8 does not support javafx anymore. Try using an older version.
https://www.raspberrypi.org/forums/viewtopic.php?f=81&t=97367
Download link http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-8u6-linux-arm-vfp-hflt.tar.gz
See if this helps.

**Comment by egoosey** [comment]
This will do what you want. https://github.com/anthonyeden/ProPresenter-Stage-Display-Python

@danielkihlgren I think this issue is closed now.
