### ISSUE TITLE
Jar File

### ISSUE THREAD

**Issue by JonathanGale** [danielkihlgren/stagedisplayviewer#14]
Removing this comment - I had a real blonde moment there, thanks!

**Comment by danielkihlgren** [comment]
I'm not following, you can download a runnable jar under releases https://github.com/danielkihlgren/stagedisplayviewer/releases
Changing configuration is done in config.properties.
Are there any specific option you need help with?

**Comment by JonathanGale** [comment]
My mistake, I had a real blond moment there. Feel free to delete the comment.
