### ISSUE TITLE
Enhancements Request

### ISSUE THREAD

**Issue by JonathanGale** [danielkihlgren/stagedisplayviewer#15]
Thanks for creating this! 
I'm going to use it in our church to overlay lyrics on our broadcast mix, and as I'm testing a couple things come to mind that it would be great to see added:

-Add the option for fade times between slides, instead of straight cuts.
-Make screen output size configurable, so users can force a particular resolution.
-Allow for other text alignments like vertically centred, or horizontally left.
-Some way to have more control on the ProPresenter end to decide where the line break should be on certain slides. 2 spaces might work at the end of a line, as ProPresenter will just ignore them, but if it passes them over the network is another question.
-Ability to auto-capitalize the start of every line.

Thanks again for creating this, I'd been hunting for months for something to pass out ProPresenter lyrics over the network instead of SDI cables. This does it nicely!

**Comment by danielkihlgren** [comment]
All features implemented
