### ISSUE TITLE
Enhancements requests - crossfading, vertical alignment

### ISSUE THREAD

**Issue by JonathanGale** [danielkihlgren/stagedisplayviewer#17]
Hey guys,

Thanks again for this software! It's opened a lot of options for our Sunday mornings with live streaming.

If you could add a vertical alignment option it would help, so it's not only bottom aligned. Changing slides from 1 line to 4 lines looks weird, because it stacks from the bottom up.
Cross-fading between slides would also smooth transitions, currently it's a fade out then fade in.
When fading to black/no lyrics, the fade time is ignored, it just instantly cuts.

**Comment by danielkihlgren** [comment]
Cross-fading will require a larger code rewrite.
