### ISSUE TITLE
Add a config parameter to have the application open in windowed mode and not fullscreen 

### ISSUE THREAD

**Issue by egoosey** [danielkihlgren/stagedisplayviewer#19]
Hello,

Love the application! We would like to request the ability to define in the config file if the application opens in fullscreen or not. We use it in windowed mode because screen real estate is at a premium due to the current workflow. Thanks!

**Comment by egoosey** [comment]
@danielkihlgren Do you think this is a viable feature request?

**Comment by danielkihlgren** [comment]
I can look into it.

**Comment by danielkihlgren** [comment]
Fixed, will be included in next release.

**Comment by danielkihlgren** [comment]
This is now available in the newest release
