### ISSUE TITLE
Option to transform text to Uppercase

### ISSUE THREAD

**Issue by playbackfreedom** [danielkihlgren/stagedisplayviewer#24]
This tool is incredible! Thank you!

I wanted to just see if there could be an option added to transform the text to Uppercase

**Comment by leorac** [comment]
The option exists but it doesn't work right now

**Comment by danielkihlgren** [comment]
There was a property called CAPITALIZE_LINES that capitalized the first letter in every line

A new property called CAPITALIZE_TEXT has now been added that capitalizes everything
