### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by jgreco0034** [danielkihlgren/stagedisplayviewer#25]
Hello, great program!

I am however having issue with changing the background color. In running the batch file I see the following warning when searching for style:

WARNING: Resource "file:///E:/GitHub Stream/styles.css" not found.

I have also changed the color (trying to go to chroma green) to #00ff00, #0f0, #0,255,0. And none work, as I don't believe the file is being found. The file path is correct and I have reinstalled multiple times on multiple computers. Any help would be great, thank you.

**Comment by danielkihlgren** [comment]
Issue was that path contained whitespaces. A fix has been checked in and will be released in upcoming release.
