### ISSUE TITLE
Not working with Blank Slides

### ISSUE THREAD

**Issue by wiebecommajonas** [danielkihlgren/stagedisplayviewer#26]
The program seems to stop when transitioning from a text slide to a blank slide / background slide (no text). It just shows the previous slide's text and when the next slide is supposed to show, it just doesn't. Restarting the program seemed to help until there was a blank slide again.

Our workaround for that was to use "Clear Slide" (F2) instead of using blank slides.

**Comment by danielkihlgren** [comment]
I'm not able to reproduce the error. Can you give more info. What version of stagedisplayviewer are you using, what version of propresenter and are you running propresenter in windows/mac?
Can you test again and start the program from a terminal window and show the output there when it hangs.

I verified behaviour with empty slides and it works fine.

**Comment by wiebecommajonas** [comment]
I have tried this with version 1.5 and ProPresenter 6. When I tested it again with version 1.6 of stagedisplayviewer it worked.

**Comment by danielkihlgren** [comment]
Good that it works.
