### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by davidslee217** [danielkihlgren/stagedisplayviewer#29]
In the screenshots of it in action, there is an example of the OBS image behind the text. I have not been able to get it to successfully have no/transparent background using the css -fx-background-color:transparent;.

**Comment by danielkihlgren** [comment]
Set the color in the .css-file to this:

    -fx-background-color: #111111;

Then add a Color key filter in OBS to the stage display source with settings.

    Key Color Type: Custom
    Key Color: #111111 (#ff111111)
    Similarity: 1
