### ISSUE TITLE
Crashes after selecting a Propresenter slide with no text

### ISSUE THREAD

**Issue by wyount** [danielkihlgren/stagedisplayviewer#30]
During songs, there are instrumentals where our media person will just select a blank motion background with no text. When she clicks back on a slide with text to continue the song, the application is no longer sending the text to OBS. Here is the error:

20:09:25.104 Debug Slide text parsed: O' praise the One who paid my debt
And raised this life up from the dead
<?xml version="1.0"?><StageDisplayData><Fields><Field type="clock" clockFormat="1" label="Clock" identifier="Clock">08:09 PM</Field><Field type="countdown" running="0" overrun="0" label="Countdown 1" identifier="Timer1">00:00:00</Field><Field type="countdownToTime" running="0" overrun="0" label="Countdown 2" identifier="Timer2">00:00:00</Field><Field type="countdown" running="0" overrun="0" label="Ellapsed Time" identifier="Timer3">00:00:00</Field><Field label="Current Slide" identifier="CurrentSlide" type="slide">
</Field><Field label="Next Slide" identifier="NextSlide" type="slide">I hear the Savior say
Thy strength indeed is small
</Field><Field label="Current Slide Notes" identifier="CurrentSlideNotes" type="slideNotes"> </Field><Field label="Next Slide Notes" identifier="NextSlideNotes" type="slideNotes"> </Field><Field label="Message" identifier="Message" type="message"> </Field><Field type="countdown" running="1" label="Video Counter" identifier="VideoCounter">- - : - - : - -</Field><Field label="Chord Chart" identifier="ChordChart" type="chordChart"></Field></Fields></StageDisplayData>
20:09:25.888 Info RAW XML: <?xml version="1.0"?><StageDisplayData><Fields><Field type="clock" clockFormat="1" label="Clock" identifier="Clock">08:09 PM</Field><Field type="countdown" running="0" overrun="0" label="Countdown 1" identifier="Timer1">00:00:00</Field><Field type="countdownToTime" running="0" overrun="0" label="Countdown 2" identifier="Timer2">00:00:00</Field><Field type="countdown" running="0" overrun="0" label="Ellapsed Time" identifier="Timer3">00:00:00</Field><Field label="Current Slide" identifier="CurrentSlide" type="slide">
</Field><Field label="Next Slide" identifier="NextSlide" type="slide">I hear the Savior say
Thy strength indeed is small
</Field><Field label="Current Slide Notes" identifier="CurrentSlideNotes" type="slideNotes"> </Field><Field label="Next Slide Notes" identifier="NextSlideNotes" type="slideNotes"> </Field><Field label="Message" identifier="Message" type="message"> </Field><Field type="countdown" running="1" label="Video Counter" identifier="VideoCounter">- - : - - : - -</Field><Field label="Chord Chart" identifier="ChordChart" type="chordChart"></Field></Fields></StageDisplayData>
**20:09:25.888 Debug Slide notes:
20:09:25.889 Debug Slide text unparsed:

Exception in thread "Thread-4" java.lang.ArrayIndexOutOfBoundsException: -1
        at se.pingstteknik.propresenter.stagedisplayviewer.util.ConcatenateRowsTranslator.reconstructTextFromRows(ConcatenateRowsTranslator.java:38)
        at se.pingstteknik.propresenter.stagedisplayviewer.util.ConcatenateRowsTranslator.transformSceneText(ConcatenateRowsTranslator.java:20)
        at se.pingstteknik.propresenter.stagedisplayviewer.runner.LowerKeyHandler.update(LowerKeyHandler.java:116)
        at se.pingstteknik.propresenter.stagedisplayviewer.runner.LowerKeyHandler.run(LowerKeyHandler.java:76)
        at java.lang.Thread.run(Unknown Source)**

![StageDislayViewer](https://user-images.githubusercontent.com/1900601/79058294-c6df8300-7c31-11ea-8bec-22234535f663.png)

**Comment by danielkihlgren** [comment]
Fixed in version 1.7.0
