### ISSUE TITLE
Unable to connect to Stage Display

### ISSUE THREAD

**Issue by happybandit360** [danielkihlgren/stagedisplayviewer#31]
We are using ProPresenter 5. I have been trying to get the Stage Display Viewer to show text, but have been unsuccessful. I tried using the .bat file today and received this information:
https://gyazo.com/b71fda62ac451060f581c725bff43b25

I believe I have the Remote Stage Display Server Settings set correctly
https://gyazo.com/10e15fe73f14913c56e0363d0046f924
according to the config file - https://hatebin.com/hmcfhcegog

I am not sure if this is an issue with ProPresenter, Stage Display Viewer, or just user error, so any information you could provide would be greatly appreciated.

**Comment by danielkihlgren** [comment]
Try java version 8

**Comment by happybandit360** [comment]
Updating Java fixed the issue. Thank you very much.
