### ISSUE TITLE
Unable to get 1.7 or 1.6 to work

### ISSUE THREAD

**Issue by dwightAhudson** [danielkihlgren/stagedisplayviewer#32]
I was following a tutorial found [here](https://www.youtube.com/watch?v=brzCXJwOUNc)

It made mention of this repository so I began giving it a try.  

When I attempted to use the 1.6 version with JDK SE 14 installed I get the following error:
![Screen Shot 2020-05-02 at 1 53 41 PM](https://user-images.githubusercontent.com/34527825/80871868-6960b400-8c7c-11ea-85e4-f7b82360e7be.png)

I am unsure if there is an issue with jar file in the download or the version of Java.  Any help would be appreciated.

When I attempted v1.7 there was no jar file in the download folder.  I was unsure if I needed to build this first and then run the file.  Any help would be appreciated.

**Comment by danielkihlgren** [comment]
https://github.com/danielkihlgren/stagedisplayviewer/releases/download/v1.7.0/StageDisplayViewer-v1.7.0.zip should contain the jar file.
Regarding the javafx error, this is how java handles javafx. It used to be bundled in java and this was developed using java 8 and should work with that. I have not verified newer versions of java and it seems that it is not bundled with those.
So try download java 8 and hopefully it will work.
