### ISSUE TITLE
Working between Mac and PC to send lyrics

### ISSUE THREAD

**Issue by dswartzlander** [danielkihlgren/stagedisplayviewer#33]
Was wondering what I could be doing wrong. I was able to get this to work between two pc on the same network but not able to get it to work between a mac with pro presenter 6 sending the information to a pc. It just doesn't send any data across to the stage display viewer on the PC. Is it possible to send over network between Mac and PC or is there possibly a setting on the Mac that is not working properly. The Mac currently send out the stage display over an HDMI cable to a projector to send the image to the wall in the back of the room.

**Comment by danielkihlgren** [comment]
I’m running the same setup and it works. Start stage display viewer from terminal/cmd and look what the debug output says.
