### ISSUE TITLE
Option to add padding to bottom of screen

### ISSUE THREAD

**Issue by anthonyeden** [danielkihlgren/stagedisplayviewer#9]
It's be great if we could add an option to add spacing to the bottom of the screen (below the last line) so it isn't as 'tight' with the bottom of the output frame.

**Comment by danielkihlgren** [comment]
This feature is now available in release v1.4.0 https://github.com/danielkihlgren/stagedisplayviewer/releases/tag/v1.4.0

**Comment by anthonyeden** [comment]
Wow, thank you so much @danielkihlgren! This is incredible software. I used it on a live stream yesterday for the first time.

I have a few more requests, but it'd be presumptuous of me to assume you want to do all this or have the time. So feel free to do any of this if you think it's be useful, but don't in any way feel obliged:

* Option to change BG colour to any RGB value
* Option to add drop-shadow with configurable size, distance, and colour.
* More resilience (auto-reconnect) if the main ProPresenter PC is restarted or goes down for a bit.

**Comment by danielkihlgren** [comment]
Thanks for the input. The background color can be changed by modifying the styles.css file. I think there are som black shadow right now, see if it's sufficient. I have been playing around a little with this before but have not found a perfect solution yet. I can see if get some time over to expose some more parameters for configuring the shadow. You can try do some testing with the current options.
Are you using atem products for adding the lower key?

I'll add feature requests for those. #10 and #11
